# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ae8017aea53e9ba30a3eccd80030a73cb08062c3e433bae1235d807ccb249d4cca9abc3a94c99c1962ac355647aae361f3c477fcdeecd8a34ccfe809cc19d9a

test:
  secret_key_base: 3e42c84b7a7aefb95cdab5385f5ce41fe6cef6820f236447ef250b7183eee9674ba0aca9146053a8da4b5ab473194faa46903215f2b6c487e09632f7998c881b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
